-- Criação da base de dados
CREATE DATABASE IF NOT EXISTS INFINITY;

-- Utilizando o BD criado
USE INFINITY;

CREATE TABLE IF NOT EXISTS STUDENTS(
	REGISTRATION INT(5) NOT NULL PRIMARY KEY,
    NAME VARCHAR(30),
    EMAIL VARCHAR(50)
);

/*
	Muito cuidado, 
    A instrução drop nao tem volta
*/
DROP TABLE IF EXISTS STUDENTS;
DROP DATABASE IF EXISTS INFINITY;

ALTER TABLE STUDENTS ADD(
	PHONE VARCHAR(9),
    COURSE VARCHAR(40)
);

ALTER TABLE STUDENTS DROP COLUMN COURSE;

ALTER TABLE STUDENTS MODIFY PHONE VARCHAR(11);

ALTER TABLE STUDENTS RENAME TO STUDENTS_DETAILS;

ALTER TABLE STUDENTS_DETAILS RENAME COLUMN PHONE TO CELLPHONE;

INSERT INTO STUDENTS_DETAILS VALUES
	(12345,'Gabriel','gabriel@email.com','12345678912');

INSERT INTO STUDENTS_DETAILS VALUES
	(12346,'Rafael','Rafael@email.com','12345678913');

UPDATE STUDENTS_DETAILS SET 
	NAME = 'Gabriel Fernandez'
WHERE 
    REGISTRATION = 12345;

SELECT *FROM STUDENTS_DETAILS;

DELETE FROM STUDENTS_DETAILS WHERE NAME = 'Rafael';	

SELECT EMAIL, NAME, CELLPHONE FROM STUDENTS_DETAILS;

SELECT * FROM STUDENTS_DETAILS ORDER BY NAME DESC;

SELECT * FROM STUDENTS_DETAILS
WHERE NAME LIKE '_a%';

-- atividade
INSERT INTO STUDENTS_DETAILS VALUES
	(12348,'Matheus','Matheus@email.com','12345678914'),
	(12349,'Lucas','Lucas@email.com','12345678916'),
	(12350,'Marcele','Marcele@email.com','12345678916'),
	(12351,'Luciana','Luciana@email.com','12345678917');

SELECT * FROM STUDENTS_DETAILS ORDER BY REGISTRATION ASC;

SELECT * FROM STUDENTS_DETAILS
WHERE NAME LIKE '%L'; -- Terminado em l

SELECT * FROM STUDENTS_DETAILS
WHERE NAME LIKE '%L%E'; -- L em qualquer lugar e terminado em e

SELECT * FROM STUDENTS_DETAILS
WHERE NAME LIKE '%E_'; -- 'e' sendo a penultima letra


-- avançando no material
ALTER TABLE STUDENTS_DETAILS ADD COLUMN
	AGE INT;

UPDATE STUDENTS_DETAILS SET -- Tenho que fazer isso um a um
	AGE = '24'
WHERE NAME = 'Marcele';

-- Media feita de diferente formas
SELECT AVG(AGE) AS 'MÉDIA' FROM STUDENTS_DETAILS;
SELECT LEFT(AVG(AGE),2) AS 'MÉDIA' FROM STUDENTS_DETAILS;	
SELECT CAST(AVG(AGE)AS SIGNED) AS 'MÉDIA' FROM STUDENTS_DETAILS;




